const Database = require('better-sqlite3');
const path = require('path');
const crypto = require('crypto');

const DB_PATH = path.join(__dirname, '..', 'cards.db');
const db = new Database(DB_PATH);
db.pragma('journal_mode = WAL');

// Create table
db.exec(`
  CREATE TABLE IF NOT EXISTS cards (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    issuer TEXT NOT NULL,
    card_type TEXT NOT NULL,
    network TEXT NOT NULL,
    annual_fee REAL DEFAULT 0,
    joining_fee REAL DEFAULT 0,
    interest_rate REAL,
    cashback_rate REAL,
    rewards_rate REAL,
    rewards_type TEXT,
    welcome_bonus TEXT,
    features TEXT DEFAULT '[]',
    benefits TEXT DEFAULT '[]',
    eligibility TEXT DEFAULT '{}',
    fees TEXT DEFAULT '{}',
    image_url TEXT,
    card_color TEXT DEFAULT '#1a1a2e',
    card_gradient TEXT DEFAULT 'linear-gradient(135deg, #1a1a2e 0%, #16213e 100%)',
    rating REAL DEFAULT 4.0,
    popularity_score INTEGER DEFAULT 0,
    is_popular INTEGER DEFAULT 0,
    highlight TEXT,
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now'))
  )
`);

const cards = [
    { name: "HDFC Regalia Gold", slug: "hdfc-regalia-gold", issuer: "HDFC Bank", card_type: "credit", network: "Visa", annual_fee: 2500, joining_fee: 2500, interest_rate: 3.49, cashback_rate: 0, rewards_rate: 4, rewards_type: "points", welcome_bonus: "10,000 reward points", highlight: "4X reward points on all spends", card_color: "#1a237e", card_gradient: "linear-gradient(135deg, #1a237e, #3949ab)", rating: 4.6, popularity_score: 95, is_popular: 1, features: ["Airport lounge access", "Golf privileges", "Concierge service", "Milestone benefits"], benefits: ["Complimentary lounge visits", "1% fuel surcharge waiver", "Buy 1 Get 1 movies", "Travel insurance ₹1 Cr"], eligibility: { minIncome: 1200000, minAge: 21, maxAge: 60, creditScore: 750 }, fees: { annualFee: 2500, renewalFee: 2500, latePenalty: 1200, cashAdvance: "2.5%" } },
    { name: "SBI SimplyCLICK", slug: "sbi-simplyclick", issuer: "SBI Card", card_type: "credit", network: "Visa", annual_fee: 499, joining_fee: 499, interest_rate: 3.35, cashback_rate: 0, rewards_rate: 5, rewards_type: "points", welcome_bonus: "₹500 Amazon voucher", highlight: "10X rewards on online spends", card_color: "#1b5e20", card_gradient: "linear-gradient(135deg, #1b5e20, #43a047)", rating: 4.4, popularity_score: 92, is_popular: 1, features: ["10X rewards on partners", "Online shopping", "Fuel surcharge waiver", "EMI conversion"], benefits: ["10X on Amazon, BookMyShow", "SBI offers", "Contactless", "Fuel waiver"], eligibility: { minIncome: 300000, minAge: 21, maxAge: 60, creditScore: 700 }, fees: { annualFee: 499, renewalFee: 499, latePenalty: 950, cashAdvance: "2.5%" } },
    { name: "ICICI Amazon Pay", slug: "icici-amazon-pay", issuer: "ICICI Bank", card_type: "credit", network: "Visa", annual_fee: 0, joining_fee: 0, interest_rate: 3.4, cashback_rate: 5, rewards_rate: 0, rewards_type: "cashback", welcome_bonus: "₹750 cashback", highlight: "5% cashback on Amazon", card_color: "#ff6f00", card_gradient: "linear-gradient(135deg, #ff6f00, #ffa000)", rating: 4.5, popularity_score: 98, is_popular: 1, features: ["No annual fee", "Cashback on all spends", "Amazon Prime", "No-cost EMI"], benefits: ["5% on Amazon", "2% digital wallets", "1% others", "₹750 welcome"], eligibility: { minIncome: 300000, minAge: 21, maxAge: 65, creditScore: 700 }, fees: { annualFee: 0, renewalFee: 0, latePenalty: 1100, cashAdvance: "2.5%" } },
    { name: "Axis Magnus", slug: "axis-magnus", issuer: "Axis Bank", card_type: "credit", network: "Visa", annual_fee: 12500, joining_fee: 12500, interest_rate: 3.4, cashback_rate: 0, rewards_rate: 12, rewards_type: "points", welcome_bonus: "25,000 EDGE points", highlight: "35X EDGE reward points on travel", card_color: "#4a148c", card_gradient: "linear-gradient(135deg, #4a148c, #8e24aa)", rating: 4.7, popularity_score: 88, is_popular: 1, features: ["Premium lounge worldwide", "Meet & greet", "24/7 concierge", "Milestone rewards"], benefits: ["35X on Axis travel", "Priority Pass", "Spa & golf", "Travel insurance ₹3 Cr"], eligibility: { minIncome: 2400000, minAge: 21, maxAge: 60, creditScore: 780 }, fees: { annualFee: 12500, renewalFee: 12500, latePenalty: 1300, cashAdvance: "2.5%" } },
    { name: "HDFC Millennia", slug: "hdfc-millennia", issuer: "HDFC Bank", card_type: "credit", network: "Mastercard", annual_fee: 1000, joining_fee: 1000, interest_rate: 3.49, cashback_rate: 5, rewards_rate: 0, rewards_type: "cashback", welcome_bonus: "1000 cashback points", highlight: "5% cashback on Amazon, Flipkart, Swiggy", card_color: "#006064", card_gradient: "linear-gradient(135deg, #006064, #0097a7)", rating: 4.3, popularity_score: 90, is_popular: 1, features: ["Online cashback", "EMI conversion", "Dining privileges", "Contactless"], benefits: ["5% on select partners", "2.5% online", "1% offline", "Zomato Pro"], eligibility: { minIncome: 400000, minAge: 21, maxAge: 60, creditScore: 720 }, fees: { annualFee: 1000, renewalFee: 1000, latePenalty: 1100, cashAdvance: "2.5%" } },
    { name: "Amex Platinum Travel", slug: "amex-platinum-travel", issuer: "American Express", card_type: "credit", network: "Amex", annual_fee: 3500, joining_fee: 3500, interest_rate: 3.5, cashback_rate: 0, rewards_rate: 5, rewards_type: "miles", welcome_bonus: "5,000 bonus points", highlight: "Best-in-class travel rewards", card_color: "#37474f", card_gradient: "linear-gradient(135deg, #37474f, #546e7a)", rating: 4.5, popularity_score: 82, is_popular: 0, features: ["Airport lounge", "Travel insurance", "Fraud protection", "Global assist"], benefits: ["5X on travel", "Complimentary lounge", "Zero liability", "24/7 global assist"], eligibility: { minIncome: 600000, minAge: 18, maxAge: 65, creditScore: 750 }, fees: { annualFee: 3500, renewalFee: 3500, latePenalty: 800, cashAdvance: "3.5%" } },
    { name: "Kotak 811 Dream Different", slug: "kotak-811-dream", issuer: "Kotak Mahindra", card_type: "credit", network: "Visa", annual_fee: 0, joining_fee: 0, interest_rate: 3.29, cashback_rate: 0, rewards_rate: 2, rewards_type: "points", welcome_bonus: null, highlight: "No annual fee, great for beginners", card_color: "#b71c1c", card_gradient: "linear-gradient(135deg, #b71c1c, #d32f2f)", rating: 4.0, popularity_score: 75, is_popular: 0, features: ["Zero annual fee", "Easy approval", "EMI on calls", "Contactless"], benefits: ["2 points per ₹100", "Fuel waiver", "No fees", "Easy EMI"], eligibility: { minIncome: 200000, minAge: 21, maxAge: 65, creditScore: 650 }, fees: { annualFee: 0, renewalFee: 0, latePenalty: 700, cashAdvance: "2.5%" } },
    { name: "HSBC Cashback", slug: "hsbc-cashback", issuer: "HSBC", card_type: "credit", network: "Visa", annual_fee: 750, joining_fee: 0, interest_rate: 3.49, cashback_rate: 1.5, rewards_rate: 0, rewards_type: "cashback", welcome_bonus: "₹750 cashback", highlight: "1.5% unlimited cashback on all spends", card_color: "#e65100", card_gradient: "linear-gradient(135deg, #e65100, #f57c00)", rating: 4.2, popularity_score: 70, is_popular: 0, features: ["Unlimited cashback", "No cap", "Easy redemption", "Auto-credit"], benefits: ["1.5% everywhere", "Auto monthly credit", "No minimum", "Welcome offer"], eligibility: { minIncome: 400000, minAge: 21, maxAge: 60, creditScore: 720 }, fees: { annualFee: 750, renewalFee: 750, latePenalty: 900, cashAdvance: "2.5%" } },
    { name: "IndusInd Platinum Aura", slug: "indusind-platinum-aura", issuer: "IndusInd Bank", card_type: "credit", network: "Mastercard", annual_fee: 0, joining_fee: 0, interest_rate: 3.25, cashback_rate: 0, rewards_rate: 2, rewards_type: "points", welcome_bonus: "2000 reward points", highlight: "Lifetime free with great rewards", card_color: "#0d47a1", card_gradient: "linear-gradient(135deg, #0d47a1, #1976d2)", rating: 4.1, popularity_score: 68, is_popular: 0, features: ["Lifetime free", "Reward points", "Movie discounts", "Fuel waiver"], benefits: ["2 pts/₹100", "Buy 1 Get 1 movies", "Fuel waiver", "No fees"], eligibility: { minIncome: 250000, minAge: 21, maxAge: 65, creditScore: 680 }, fees: { annualFee: 0, renewalFee: 0, latePenalty: 800, cashAdvance: "2.5%" } },
    { name: "Yes Bank Marquee", slug: "yes-bank-marquee", issuer: "Yes Bank", card_type: "credit", network: "Visa", annual_fee: 5000, joining_fee: 5000, interest_rate: 3.49, cashback_rate: 0, rewards_rate: 8, rewards_type: "points", welcome_bonus: "10,000 reward points", highlight: "Premium rewards with golf & lounge", card_color: "#311b92", card_gradient: "linear-gradient(135deg, #311b92, #512da8)", rating: 4.3, popularity_score: 65, is_popular: 0, features: ["Lounge access", "Golf", "Concierge", "Dining offers"], benefits: ["8X on dining", "4X on travel", "Unlimited lounge", "Golf sessions"], eligibility: { minIncome: 1000000, minAge: 21, maxAge: 60, creditScore: 750 }, fees: { annualFee: 5000, renewalFee: 5000, latePenalty: 1100, cashAdvance: "2.5%" } },
    { name: "RBL Shoprite", slug: "rbl-shoprite", issuer: "RBL Bank", card_type: "credit", network: "Mastercard", annual_fee: 0, joining_fee: 0, interest_rate: 3.49, cashback_rate: 5, rewards_rate: 0, rewards_type: "cashback", welcome_bonus: "10% first 3 txns", highlight: "5% cashback on grocery shopping", card_color: "#004d40", card_gradient: "linear-gradient(135deg, #004d40, #00897b)", rating: 4.0, popularity_score: 60, is_popular: 0, features: ["Grocery cashback", "Fuel waiver", "No fee", "Contactless"], benefits: ["5% groceries", "2.5% online", "1% other", "No fee ever"], eligibility: { minIncome: 200000, minAge: 21, maxAge: 60, creditScore: 650 }, fees: { annualFee: 0, renewalFee: 0, latePenalty: 750, cashAdvance: "2.5%" } },
    { name: "Axis Flipkart", slug: "axis-flipkart", issuer: "Axis Bank", card_type: "credit", network: "Visa", annual_fee: 500, joining_fee: 500, interest_rate: 3.4, cashback_rate: 5, rewards_rate: 0, rewards_type: "cashback", welcome_bonus: "₹500 Flipkart voucher", highlight: "5% unlimited cashback on Flipkart", card_color: "#1565c0", card_gradient: "linear-gradient(135deg, #1565c0, #42a5f5)", rating: 4.4, popularity_score: 87, is_popular: 1, features: ["Flipkart cashback", "Myntra benefits", "EMI", "Contactless"], benefits: ["5% Flipkart & Myntra", "4% partners", "1.5% all other", "Welcome voucher"], eligibility: { minIncome: 300000, minAge: 21, maxAge: 60, creditScore: 700 }, fees: { annualFee: 500, renewalFee: 500, latePenalty: 1000, cashAdvance: "2.5%" } },
    { name: "HDFC Infinia", slug: "hdfc-infinia", issuer: "HDFC Bank", card_type: "credit", network: "Visa", annual_fee: 12500, joining_fee: 12500, interest_rate: 3.49, cashback_rate: 0, rewards_rate: 5, rewards_type: "points", welcome_bonus: "12,500 reward points", highlight: "India's most premium credit card", card_color: "#212121", card_gradient: "linear-gradient(135deg, #212121, #616161)", rating: 4.9, popularity_score: 85, is_popular: 1, features: ["Unlimited lounge", "Concierge 24/7", "Premium golf", "Club Marriott"], benefits: ["5X all spends", "Unlimited intl lounge", "Premium hotels", "Travel insurance ₹5 Cr"], eligibility: { minIncome: 3000000, minAge: 21, maxAge: 60, creditScore: 800 }, fees: { annualFee: 12500, renewalFee: 12500, latePenalty: 1300, cashAdvance: "2.5%" } },
    { name: "SBI BPCL Octane", slug: "sbi-bpcl-octane", issuer: "SBI Card", card_type: "credit", network: "Visa", annual_fee: 1499, joining_fee: 1499, interest_rate: 3.35, cashback_rate: 0, rewards_rate: 13, rewards_type: "points", welcome_bonus: "6,000 points on BPCL", highlight: "13X rewards on BPCL fuel", card_color: "#f57f17", card_gradient: "linear-gradient(135deg, #f57f17, #fbc02d)", rating: 4.2, popularity_score: 72, is_popular: 0, features: ["Fuel rewards", "Dining", "Movie discounts", "Surcharge waiver"], benefits: ["13X BPCL fuel", "5X dining/grocery", "1% surcharge waiver", "Milestone bonus"], eligibility: { minIncome: 500000, minAge: 21, maxAge: 60, creditScore: 720 }, fees: { annualFee: 1499, renewalFee: 1499, latePenalty: 950, cashAdvance: "2.5%" } },
    { name: "Citi Cashback", slug: "citi-cashback", issuer: "Citibank", card_type: "credit", network: "Mastercard", annual_fee: 500, joining_fee: 500, interest_rate: 3.49, cashback_rate: 5, rewards_rate: 0, rewards_type: "cashback", welcome_bonus: "₹3,000 cashback", highlight: "5% cashback on phone & utility bills", card_color: "#01579b", card_gradient: "linear-gradient(135deg, #01579b, #0288d1)", rating: 4.1, popularity_score: 67, is_popular: 0, features: ["Phone bill cashback", "Utility cashback", "Movies", "Dining"], benefits: ["5% phone bills", "5% utilities", "0.5% all other", "Welcome cashback"], eligibility: { minIncome: 400000, minAge: 23, maxAge: 60, creditScore: 720 }, fees: { annualFee: 500, renewalFee: 500, latePenalty: 1000, cashAdvance: "2.5%" } },
    // Debit Cards
    { name: "HDFC EasyShop Platinum", slug: "hdfc-easyshop-platinum", issuer: "HDFC Bank", card_type: "debit", network: "Visa", annual_fee: 750, joining_fee: 0, cashback_rate: 1, rewards_type: "cashback", highlight: "1% cashback on all POS transactions", card_color: "#1a237e", card_gradient: "linear-gradient(135deg, #1a237e, #3949ab)", rating: 4.0, popularity_score: 70, is_popular: 0, features: ["Cashback on POS", "International", "ATM", "Tap to pay"], benefits: ["1% at POS", "International txns", "Free ATM", "Insurance"], eligibility: { minBalance: 10000, minAge: 18, maxAge: 70 }, fees: { annualFee: 750, atmFee: "Free 5/month", internationalFee: "3.5%" } },
    { name: "SBI Global International", slug: "sbi-global-international", issuer: "SBI", card_type: "debit", network: "Visa", annual_fee: 350, joining_fee: 0, rewards_rate: 1, rewards_type: "points", highlight: "Accepted worldwide with reward points", card_color: "#1b5e20", card_gradient: "linear-gradient(135deg, #1b5e20, #388e3c)", rating: 3.9, popularity_score: 75, is_popular: 0, features: ["Global acceptance", "Online shopping", "ATM access", "Rewards"], benefits: ["Reward points", "Global acceptance", "Online shopping", "ATM worldwide"], eligibility: { minBalance: 5000, minAge: 18, maxAge: 70 }, fees: { annualFee: 350, atmFee: "Free 5/month", internationalFee: "3.5%" } },
    { name: "ICICI Coral Debit", slug: "icici-coral-debit", issuer: "ICICI Bank", card_type: "debit", network: "Visa", annual_fee: 599, joining_fee: 0, rewards_rate: 2, rewards_type: "points", highlight: "2X reward points + dining privileges", card_color: "#e65100", card_gradient: "linear-gradient(135deg, #e65100, #f57c00)", rating: 4.1, popularity_score: 65, is_popular: 0, features: ["Reward points", "Dining discounts", "Movies", "Lounge"], benefits: ["2X rewards", "Culinary treats", "Movie offers", "1 lounge/quarter"], eligibility: { minBalance: 15000, minAge: 18, maxAge: 70 }, fees: { annualFee: 599, atmFee: "Free 8/month", internationalFee: "3.5%" } },
    { name: "Axis Priority Debit", slug: "axis-priority-debit", issuer: "Axis Bank", card_type: "debit", network: "Visa", annual_fee: 0, joining_fee: 0, rewards_rate: 2, rewards_type: "points", highlight: "Priority banking with free lounge access", card_color: "#4a148c", card_gradient: "linear-gradient(135deg, #4a148c, #7b1fa2)", rating: 4.2, popularity_score: 68, is_popular: 0, features: ["Priority banking", "Lounge", "Higher limits", "Rewards"], benefits: ["Free lounge", "Higher ATM limit", "Priority service", "2X rewards"], eligibility: { minBalance: 200000, minAge: 18, maxAge: 70 }, fees: { annualFee: 0, atmFee: "Free unlimited", internationalFee: "2%" } },
    { name: "Kotak Privy League Platinum", slug: "kotak-privy-league", issuer: "Kotak Mahindra", card_type: "debit", network: "Mastercard", annual_fee: 0, joining_fee: 0, cashback_rate: 0.5, rewards_type: "cashback", highlight: "Premium debit with cashback & lounge", card_color: "#880e4f", card_gradient: "linear-gradient(135deg, #880e4f, #c2185b)", rating: 4.0, popularity_score: 55, is_popular: 0, features: ["Cashback", "Lounge", "High limit", "Concierge"], benefits: ["0.5% cashback", "4 lounge/year", "₹2L ATM limit", "Concierge"], eligibility: { minBalance: 500000, minAge: 18, maxAge: 70 }, fees: { annualFee: 0, atmFee: "Free unlimited", internationalFee: "2.5%" } },
    // Forex Cards
    { name: "HDFC ForexPlus", slug: "hdfc-forexplus", issuer: "HDFC Bank", card_type: "forex", network: "Visa", annual_fee: 0, joining_fee: 500, highlight: "Load 22 currencies, zero cross-currency charges", card_color: "#0d47a1", card_gradient: "linear-gradient(135deg, #0d47a1, #1976d2)", rating: 4.3, popularity_score: 80, is_popular: 1, features: ["22 currencies", "Zero markup", "ATM worldwide", "Travel insurance"], benefits: ["22 currencies", "No cross-currency", "Emergency cash", "Insurance ₹5L"], eligibility: { minAge: 18, documents: ["Passport", "Visa", "Ticket"] }, fees: { issuanceFee: 500, reloadFee: 100, atmFee: "$2/withdrawal", inactivity: "₹75/month" } },
    { name: "ICICI Travel Card", slug: "icici-travel-card", issuer: "ICICI Bank", card_type: "forex", network: "Visa", annual_fee: 0, joining_fee: 150, highlight: "Multi-currency card with competitive rates", card_color: "#bf360c", card_gradient: "linear-gradient(135deg, #bf360c, #e64a19)", rating: 4.1, popularity_score: 72, is_popular: 0, features: ["15 currencies", "Competitive rates", "Online management", "Emergency replacement"], benefits: ["15 currencies", "Lock-in rates", "Online reload", "Zero balance fee"], eligibility: { minAge: 18, documents: ["Passport", "Visa"] }, fees: { issuanceFee: 150, reloadFee: 100, atmFee: "$1.5/withdrawal", inactivity: "₹50/month" } },
    { name: "Axis Multi-Currency Forex", slug: "axis-multi-currency-forex", issuer: "Axis Bank", card_type: "forex", network: "Visa", annual_fee: 0, joining_fee: 300, highlight: "16 currencies with doorstep delivery", card_color: "#4a148c", card_gradient: "linear-gradient(135deg, #4a148c, #7b1fa2)", rating: 4.2, popularity_score: 75, is_popular: 0, features: ["16 currencies", "Doorstep delivery", "Internet banking", "Insurance"], benefits: ["16 currencies", "Home delivery", "Internet reload", "Emergency $5000"], eligibility: { minAge: 18, documents: ["Passport", "Visa", "Ticket"] }, fees: { issuanceFee: 300, reloadFee: 75, atmFee: "$2/withdrawal", inactivity: "₹50/month" } },
    { name: "SBI Multi-Currency Forex", slug: "sbi-multi-currency-forex", issuer: "SBI", card_type: "forex", network: "Visa", annual_fee: 0, joining_fee: 100, highlight: "Budget-friendly forex from India's largest bank", card_color: "#1b5e20", card_gradient: "linear-gradient(135deg, #1b5e20, #388e3c)", rating: 3.9, popularity_score: 68, is_popular: 0, features: ["8 currencies", "SBI branch reload", "Emergency", "Balance check"], benefits: ["8 currencies", "Low fee", "SBI network", "SMS alerts"], eligibility: { minAge: 18, documents: ["Passport", "Visa"] }, fees: { issuanceFee: 100, reloadFee: 50, atmFee: "$1.75/withdrawal", inactivity: "Nil" } },
    { name: "YES Bank Forex Card", slug: "yes-bank-forex", issuer: "Yes Bank", card_type: "forex", network: "Mastercard", annual_fee: 0, joining_fee: 250, highlight: "12 currencies with Mastercard acceptance", card_color: "#311b92", card_gradient: "linear-gradient(135deg, #311b92, #512da8)", rating: 3.8, popularity_score: 55, is_popular: 0, features: ["12 currencies", "Mastercard", "Online management", "Free replacement"], benefits: ["12 currencies", "Mastercard acceptance", "24/7 helpline", "Free replacement"], eligibility: { minAge: 18, documents: ["Passport", "Visa"] }, fees: { issuanceFee: 250, reloadFee: 100, atmFee: "$2/withdrawal", inactivity: "₹75/month" } },
    // Prepaid Cards
    { name: "Paytm Payments Bank Card", slug: "paytm-prepaid", issuer: "Paytm", card_type: "prepaid", network: "RuPay", annual_fee: 0, joining_fee: 0, cashback_rate: 2, rewards_type: "cashback", highlight: "Instant digital card with UPI & cashback", card_color: "#01579b", card_gradient: "linear-gradient(135deg, #01579b, #0288d1)", rating: 3.8, popularity_score: 82, is_popular: 1, features: ["Instant activation", "UPI", "Online shopping", "Cashback"], benefits: ["Instant card", "2% cashback select", "Zero fee", "Easy KYC"], eligibility: { minAge: 18, documents: ["Aadhaar", "PAN"] }, fees: { issuanceFee: 0, reloadFee: 0, atmFee: "₹25", monthlyCharge: 0 } },
    { name: "FamPay Numberless Card", slug: "fampay-numberless", issuer: "FamPay", card_type: "prepaid", network: "Visa", annual_fee: 0, joining_fee: 199, rewards_rate: 1, rewards_type: "points", welcome_bonus: "FamCoins ₹50", highlight: "India's first numberless card for teens", card_color: "#6200ea", card_gradient: "linear-gradient(135deg, #6200ea, #b388ff)", rating: 4.0, popularity_score: 72, is_popular: 0, features: ["Numberless", "Parent controls", "Analytics", "Rewards"], benefits: ["Numberless security", "Parental controls", "FamCoins", "Spending insights"], eligibility: { minAge: 13, maxAge: 21, documents: ["Parent Aadhaar", "Student ID"] }, fees: { issuanceFee: 199, reloadFee: 0, atmFee: "₹20", monthlyCharge: 0 } },
    { name: "NiYO Global Card", slug: "niyo-global-card", issuer: "NiYO", card_type: "prepaid", network: "Visa", annual_fee: 0, joining_fee: 0, highlight: "Zero forex markup for international use", card_color: "#00695c", card_gradient: "linear-gradient(135deg, #00695c, #009688)", rating: 4.3, popularity_score: 76, is_popular: 1, features: ["Zero forex markup", "Free ATM", "Travel insurance", "Spending tracker"], benefits: ["0% forex markup", "Free intl ATM", "Insurance ₹20L", "Expense tracking"], eligibility: { minAge: 18, documents: ["Aadhaar", "PAN", "Passport"] }, fees: { issuanceFee: 0, reloadFee: 0, atmFee: "Free worldwide", monthlyCharge: 0 } },
    { name: "PhonePe Prepaid Card", slug: "phonepe-prepaid", issuer: "PhonePe", card_type: "prepaid", network: "RuPay", annual_fee: 0, joining_fee: 0, cashback_rate: 1.5, rewards_type: "cashback", highlight: "Seamless UPI with cashback", card_color: "#4a148c", card_gradient: "linear-gradient(135deg, #4a148c, #7b1fa2)", rating: 3.7, popularity_score: 74, is_popular: 0, features: ["UPI integration", "Cashback", "Bill payments", "Easy reload"], benefits: ["1.5% cashback select", "UPI integration", "No fee", "Instant activation"], eligibility: { minAge: 18, documents: ["Aadhaar"] }, fees: { issuanceFee: 0, reloadFee: 0, atmFee: "₹25", monthlyCharge: 0 } },
    // More credit cards
    { name: "HDFC Diners Club Black", slug: "hdfc-diners-club-black", issuer: "HDFC Bank", card_type: "credit", network: "Visa", annual_fee: 10000, joining_fee: 10000, interest_rate: 3.49, cashback_rate: 0, rewards_rate: 5, rewards_type: "points", welcome_bonus: "10,000 reward points", highlight: "10X rewards on SmartBuy + unlimited lounge", card_color: "#263238", card_gradient: "linear-gradient(135deg, #263238, #455a64)", rating: 4.8, popularity_score: 91, is_popular: 1, features: ["Unlimited lounge", "Golf", "Hotel memberships", "Reward acceleration"], benefits: ["10X SmartBuy", "Unlimited lounge", "Club Marriott", "Golf fees"], eligibility: { minIncome: 1800000, minAge: 21, maxAge: 60, creditScore: 780 }, fees: { annualFee: 10000, renewalFee: 10000, latePenalty: 1300, cashAdvance: "2.5%" } },
    { name: "Axis ACE", slug: "axis-ace", issuer: "Axis Bank", card_type: "credit", network: "Visa", annual_fee: 499, joining_fee: 499, interest_rate: 3.4, cashback_rate: 5, rewards_rate: 0, rewards_type: "cashback", highlight: "5% cashback on Google Pay bill payments", card_color: "#0277bd", card_gradient: "linear-gradient(135deg, #0277bd, #039be5)", rating: 4.3, popularity_score: 86, is_popular: 1, features: ["Google Pay cashback", "No cap", "Bill payments", "Contactless"], benefits: ["5% Google Pay bills", "4% Swiggy/Zomato", "2% all other", "Fee waiver ₹2L"], eligibility: { minIncome: 300000, minAge: 21, maxAge: 60, creditScore: 700 }, fees: { annualFee: 499, renewalFee: 499, latePenalty: 1000, cashAdvance: "2.5%" } },
    { name: "AU Small Finance LIT", slug: "au-lit-card", issuer: "AU Small Finance", card_type: "credit", network: "Visa", annual_fee: 0, joining_fee: 0, interest_rate: 2.99, rewards_rate: 3, rewards_type: "points", welcome_bonus: "₹500 Amazon voucher", highlight: "Customizable — pick your own benefits", card_color: "#e91e63", card_gradient: "linear-gradient(135deg, #e91e63, #f48fb1)", rating: 4.2, popularity_score: 77, is_popular: 0, features: ["Customizable", "Zero fee", "Choose rewards", "Flexible"], benefits: ["Pick 3 features", "Zero annual fee", "Up to 3X rewards", "Custom card"], eligibility: { minIncome: 250000, minAge: 21, maxAge: 60, creditScore: 680 }, fees: { annualFee: 0, renewalFee: 0, latePenalty: 800, cashAdvance: "2.5%" } },
    { name: "Standard Chartered Ultimate", slug: "sc-ultimate", issuer: "Standard Chartered", card_type: "credit", network: "Visa", annual_fee: 5000, joining_fee: 5000, interest_rate: 3.49, rewards_rate: 5, rewards_type: "points", welcome_bonus: "7,500 reward points", highlight: "5X rewards on international spends", card_color: "#1a237e", card_gradient: "linear-gradient(135deg, #1a237e, #1565c0)", rating: 4.4, popularity_score: 74, is_popular: 0, features: ["International rewards", "Lounge", "Golf", "Travel"], benefits: ["5X international", "Priority Pass", "Golf", "Concierge"], eligibility: { minIncome: 1200000, minAge: 21, maxAge: 60, creditScore: 750 }, fees: { annualFee: 5000, renewalFee: 5000, latePenalty: 1100, cashAdvance: "2.5%" } },
    { name: "HDFC Swiggy Card", slug: "hdfc-swiggy", issuer: "HDFC Bank", card_type: "credit", network: "Mastercard", annual_fee: 500, joining_fee: 500, interest_rate: 3.49, cashback_rate: 10, rewards_type: "cashback", welcome_bonus: "3 months Swiggy One", highlight: "10% cashback on Swiggy orders", card_color: "#e65100", card_gradient: "linear-gradient(135deg, #e65100, #ff5722)", rating: 4.3, popularity_score: 84, is_popular: 1, features: ["Swiggy cashback", "Food delivery", "Dining", "Online shopping"], benefits: ["10% Swiggy", "5% online", "1% everywhere", "Swiggy One"], eligibility: { minIncome: 300000, minAge: 21, maxAge: 60, creditScore: 700 }, fees: { annualFee: 500, renewalFee: 500, latePenalty: 1000, cashAdvance: "2.5%" } },
    { name: "OneCard Metal", slug: "onecard-metal", issuer: "OneCard", card_type: "credit", network: "Visa", annual_fee: 0, joining_fee: 0, interest_rate: 3.49, cashback_rate: 5, rewards_type: "cashback", highlight: "5X rewards on top categories — metal build", card_color: "#37474f", card_gradient: "linear-gradient(135deg, #37474f, #607d8b)", rating: 4.4, popularity_score: 83, is_popular: 1, features: ["Metal card", "App-first", "5X top categories", "No fees"], benefits: ["5X top 2 categories", "Metal build", "No fees", "Full app control"], eligibility: { minIncome: 300000, minAge: 21, maxAge: 60, creditScore: 700 }, fees: { annualFee: 0, renewalFee: 0, latePenalty: 1000, cashAdvance: "2.5%" } },
    { name: "BOB Easy Credit Card", slug: "bob-easy-credit", issuer: "Bank of Baroda", card_type: "credit", network: "RuPay", annual_fee: 0, joining_fee: 0, interest_rate: 2.99, rewards_rate: 1, rewards_type: "points", welcome_bonus: "500 bonus points", highlight: "Zero fee entry-level RuPay credit card", card_color: "#e65100", card_gradient: "linear-gradient(135deg, #e65100, #f57c00)", rating: 3.7, popularity_score: 58, is_popular: 0, features: ["Zero fee", "RuPay", "Easy EMI", "Fuel waiver"], benefits: ["1 pt/₹100", "Zero fees", "Fuel waiver", "RuPay discounts"], eligibility: { minIncome: 180000, minAge: 21, maxAge: 65, creditScore: 630 }, fees: { annualFee: 0, renewalFee: 0, latePenalty: 600, cashAdvance: "2.5%" } },
];

// Clear and re-insert
db.exec('DELETE FROM cards');

const insert = db.prepare(`
  INSERT INTO cards (id, name, slug, issuer, card_type, network, annual_fee, joining_fee, interest_rate, cashback_rate, rewards_rate, rewards_type, welcome_bonus, features, benefits, eligibility, fees, card_color, card_gradient, rating, popularity_score, is_popular, highlight)
  VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`);

const insertMany = db.transaction((cards) => {
    for (const c of cards) {
        insert.run(
            crypto.randomUUID(),
            c.name, c.slug, c.issuer, c.card_type, c.network,
            c.annual_fee || 0, c.joining_fee || 0,
            c.interest_rate || null, c.cashback_rate || null, c.rewards_rate || null,
            c.rewards_type || null, c.welcome_bonus || null,
            JSON.stringify(c.features || []), JSON.stringify(c.benefits || []),
            JSON.stringify(c.eligibility || {}), JSON.stringify(c.fees || {}),
            c.card_color || '#1a1a2e', c.card_gradient || 'linear-gradient(135deg, #1a1a2e, #16213e)',
            c.rating || 4.0, c.popularity_score || 0, c.is_popular || 0,
            c.highlight || null
        );
    }
});

insertMany(cards);

const count = db.prepare('SELECT COUNT(*) as count FROM cards').get();
console.log(`Seeded ${count.count} cards successfully!`);
db.close();
